"""Knowledge distillation from the DINOv2 backbone (teacher, frozen) into a
small student CNN — conservative scope: few epochs, checkpoint every epoch,
loss monitored at every step.

Uses the teacher features ALREADY CACHED in puma/features/ (generated by
pipeline/02_feature_extractor.py) as the target — no need to run DINOv2 again
during training, only the student (much faster).

StudentBackbone itself lives in serving/student_model.py (production depends
on it directly); this script only trains it.
"""
import os
import sys
import time

import torch
import torch.nn.functional as F

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(REPO_ROOT)
sys.path.append(os.path.join(REPO_ROOT, "serving"))
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(os.path.join(REPO_ROOT, "pipeline"))

from eval_utils import load_raw_image, make_transform
from student_model import StudentBackbone, STUDENT_CHECKPOINT_PATH
from config import BASE_PATH, FEATURES_DIR, CHECKPOINT_DIR
from utils.logger import get_logger

logger = get_logger(__name__)


def get_train_ids():
    """Split complementary to eval_utils.get_val_ids (same seed=42, 80/20) — the training images."""
    import importlib
    dataset_module = importlib.import_module("03_dataset")
    PUMAFeatureDataset = dataset_module.PUMAFeatureDataset

    full_dataset = PUMAFeatureDataset(BASE_PATH, cache_in_ram=False)
    train_size = int(0.8 * len(full_dataset))
    val_size = len(full_dataset) - train_size
    generator = torch.Generator().manual_seed(42)
    train_dataset, _ = torch.utils.data.random_split(full_dataset, [train_size, val_size], generator=generator)
    return [full_dataset.sample_ids[i] for i in train_dataset.indices]


def train(epochs: int = 8, lr: float = 1e-3, resolution: int = 1036):
    device = torch.device("cpu")
    student = StudentBackbone().to(device)
    student.train()

    optimizer = torch.optim.Adam(student.parameters(), lr=lr)
    transform = make_transform(resolution)

    train_ids = get_train_ids()
    logger.info(f"Distillation: {len(train_ids)} training images, {epochs} epochs, lr={lr}")

    # Preloads all images + target features into RAM (training set is small, fits easily)
    samples = []
    for image_id in train_ids:
        feature_path = FEATURES_DIR / f"{image_id}.pt"
        if not feature_path.exists():
            continue
        teacher_feat = torch.load(feature_path).squeeze(0)  # (384, 74, 74)
        img = load_raw_image(image_id)
        tensor = transform(img)  # (3, res, res)
        samples.append((tensor, teacher_feat))

    logger.info(f"{len(samples)} samples loaded into RAM (image + teacher target feature).")

    history = []
    for epoch in range(1, epochs + 1):
        start = time.time()
        epoch_loss = 0.0

        for tensor, teacher_feat in samples:
            optimizer.zero_grad()
            student_feat = student(tensor.unsqueeze(0)).squeeze(0)
            loss = F.mse_loss(student_feat, teacher_feat)

            if not torch.isfinite(loss):
                logger.error(f"Non-finite loss at epoch {epoch} — aborting training (safety net).")
                return student, history

            loss.backward()
            optimizer.step()
            epoch_loss += loss.item()

        avg_loss = epoch_loss / len(samples)
        elapsed = time.time() - start
        history.append(avg_loss)
        logger.info(f"Epoch {epoch}/{epochs} | loss={avg_loss:.4f} | {elapsed:.1f}s")

        os.makedirs(CHECKPOINT_DIR, exist_ok=True)
        torch.save(
            {"epoch": epoch, "model_state_dict": student.state_dict(), "loss": avg_loss},
            STUDENT_CHECKPOINT_PATH,
        )

    logger.info(f"Training complete. Final checkpoint: {STUDENT_CHECKPOINT_PATH}")
    return student, history


if __name__ == "__main__":
    train()
